### ISSUE TITLE
Unable to register plugin since migrating to esmodules

### ISSUE THREAD

**Issue by Wazbat** [autotelic/fastify-opentelemetry#70] opened 2024-08-07 21:59 UTC
Hi there,

I'm trying to migrate my application to ESM, however I now get the following error with this package.

This is the code:
```ts
import Fastify from 'fastify';
import openTelemertryPlugin from '@autotelic/fastify-opentelemetry';

export default async function makeApp() {
    const fastify = Fastify({
        logger: false
    });

    await fastify.register(openTelemertryPlugin, {
        wrapRoutes: ['/v3/search/merchant'],
        formatSpanName: (req) => (req.routeOptions?.url ? `${req.method} ${req.routeOptions.url}` : req.method)
    });
    return fastify;
}
```
And this is the error:
```
No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof fastifyOpenTelemetry' is not assignable to parameter of type 'FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>'.
      Type 'typeof fastifyOpenTelemetry' provides no match for the signature '(instance: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProvider>, opts: FastifyPluginOptions, done: (err?: Error | undefined) => void): void'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof fastifyOpenTelemetry' is not assignable to parameter of type 'FastifyPluginAsync<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>'.
      Type 'typeof fastifyOpenTelemetry' provides no match for the signature '(instance: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProvider>, opts: FastifyPluginOptions): Promise<...>'.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof fastifyOpenTelemetry' is not assignable to parameter of type 'FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>'.
```

![image](https://github.com/user-attachments/assets/295a5f46-8e98-4972-98dc-a66a60efda73)

I'm using `@autotelic/fastify-opentelemetry` version `^0.21.0` and version `^4.28.0` of fastify

**Comment by HW13** [comment] 2024-08-14 23:57
Hi @Wazbat, I'm not able to reproduce the error using the provided code example. Based on that error message and the screenshot, it looks like a TypeScript error. But I'm also unable to reproduce the error in a minimal TypeScript app. Without knowing more about your app setup there's limited help I can provide. Would you be able to provide a minimal example app that can reproduce this error?

**Comment by HW13** [comment] 2024-09-19 22:55
Closing this, as we are unable to reproduce

**Closed by HW13** 2024-09-19 22:55 UTC

**Comment by jmikedupont2** [comment] 2025-01-06 00:33
I got the same type of error here

**Comment by jmikedupont2** [comment] 2025-01-06 00:37
https://github.com/autotelic/fastify-opentelemetry/issues/74
